"""onda1: fixes de integridade, indices e JSONB

Revision ID: 73f922fd358f
Revises: 26e459a7e00a
Create Date: 2026-09-17 15:34:20.872985
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores desta revisão
revision: str = '73f922fd358f'
down_revision: str | None = '26e459a7e00a'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.alter_column('dados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)

    with op.batch_alter_table('configuracao_sistema', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('configuracao_sistema_chave_key'), type_='unique')
        batch_op.create_index('ix_config_chave_global', ['chave'], unique=True, postgresql_where=sa.text('unidade_id IS NULL'))
        batch_op.create_index('ix_config_chave_unidade', ['chave', 'unidade_id'], unique=True, postgresql_where=sa.text('unidade_id IS NOT NULL'))

    with op.batch_alter_table('conselho_classe', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_conselho_turma_aluno_etapa', ['turma_id', 'aluno_id', 'etapa'])

    with op.batch_alter_table('frequencia', schema=None) as batch_op:
        batch_op.create_index('ix_frequencia_aluno_data', ['aluno_id', 'data'], unique=False)
        batch_op.create_index('ix_frequencia_turma_data', ['turma_id', 'data'], unique=False)
        batch_op.create_unique_constraint('uix_frequencia_aluno_turma_data', ['aluno_id', 'turma_id', 'data'])

    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.alter_column('dados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.alter_column('dados',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('frequencia', schema=None) as batch_op:
        batch_op.drop_constraint('uix_frequencia_aluno_turma_data', type_='unique')
        batch_op.drop_index('ix_frequencia_turma_data')
        batch_op.drop_index('ix_frequencia_aluno_data')

    with op.batch_alter_table('conselho_classe', schema=None) as batch_op:
        batch_op.drop_constraint('uix_conselho_turma_aluno_etapa', type_='unique')

    with op.batch_alter_table('configuracao_sistema', schema=None) as batch_op:
        batch_op.drop_index('ix_config_chave_unidade', postgresql_where=sa.text('unidade_id IS NOT NULL'))
        batch_op.drop_index('ix_config_chave_global', postgresql_where=sa.text('unidade_id IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('configuracao_sistema_chave_key'), ['chave'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.alter_column('dados',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    # ### end Alembic commands ###
