"""add google_id and google_email to user

Revision ID: 7aa724d05691
Revises: a1b2c3d4
Create Date: 2026-09-11 17:22:18.318013
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores desta revisão
revision: str = '7aa724d05691'
down_revision: str | None = 'a1b2c3d4'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.alter_column('setor',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('dados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('atendido_por_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('atendido_por_nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_atendimento_aluno_id'))
        batch_op.drop_index(batch_op.f('ix_atendimento_data'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimento_data'), ['data_atendimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimento_aluno_id'), ['aluno_id'], unique=False)
        batch_op.alter_column('atendido_por_nome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('atendido_por_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dados',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('setor',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
