"""add_periodo_conselho

Revision ID: 99f0996802e6
Revises: b2c3d4e5
Create Date: 2026-09-14 15:11:14.150991
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# Identificadores desta revisão
revision: str = '99f0996802e6'
down_revision: str | None = 'b2c3d4e5'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodo_conselho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('conselho_final', sa.Boolean(), nullable=False),
    sa.Column('periodo_letivo_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['periodo_letivo_id'], ['periodo_letivo.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodo_conselho')
    # ### end Alembic commands ###
